### ISSUE TITLE
Select All Checkbox

### ISSUE THREAD

**Issue by angelamiranda11** [imelilabourne/To-do-List-App#2]
Issues: 
1. Text is not aligned with checkbox
2. When I tick the **Select All** checkbox, **Select All** is hidden. I suggest not hiding it and just leave it checked, because the user might change his mind and wants to unselect all.

![image](https://user-images.githubusercontent.com/14832233/93545406-e0c88300-f992-11ea-93e2-fbd67641cc05.png)

**Comment by imelilabourne** [comment]
For Review

**Comment by angelamiranda11** [comment]
RESOLVED
