### ISSUE TITLE
Button Font Style

### ISSUE THREAD

**Issue by angelamiranda11** [imelilabourne/To-do-List-App#3]
**Edit** and **Delete** buttons have a different font style with the rest of the elements of your application.
Design wise, it's better if they are the same font as the **Clear Completed** button. 

![image](https://user-images.githubusercontent.com/14832233/93547000-a19c3100-f996-11ea-85b4-d9106d9bc290.png)

**Comment by imelilabourne** [comment]
For Review

**Comment by angelamiranda11** [comment]
RESOLVED
